spring:
  profiles:
    active: local
    
  


---

spring:
  profiles: local  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: OCOE_DB
    password: ocoe
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
      